import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import LayoutClient from "@/components/layout-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={inter.style}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LayoutClient>
            <main className="min-h-screen overflow-auto flex">
              <Sidebar />
              <div className="flex-1">{children}</div>
            </main>
          </LayoutClient>
        </ThemeProvider>
      </body>
    </html>
  );
}
